### PR TITLE
Fix isOrganizationApigeeX() on null issue

### LINKED ISSUE #928: Saving multivalue field that is part of the Team Entity results in an error.
## Description
Saving multivalue field that is part of the Team Entity results in an error.

## Apigee Info
Apigee Edge

## Steps to Reproduce
Enable apigee_edge_teams
Add a new field that enables having multiple values /admin/config/apigee-edge/team-settings/fields
Add a new team add with least 2 values into our new field.

## Expected behaviour
Team will save.
Field values will be save

## Actual behaviour
Hit Save, will result in a 500 error.

Error message in logs is
`Error: Call to a member function isOrganizationApigeeX() on null in Drupal\apigee_edge_teams\Entity\Form\TeamForm->buildEntity() (line 165 of /app/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Entity/Form/TeamForm.php).`

Replicated using Apigee Kickstart distro

### PR DESCRIPTION
**Pull request by shishir-intelli**
Closes #928

### CODE REVIEW

File: modules/apigee_edge_teams/src/Entity/Form/TeamForm.php [hunk 1]
```diff
@@ -159,6 +159,9 @@ public function buildEntity(array $form, FormStateInterface $form_state) {
     /** @var \Drupal\apigee_edge_teams\Entity\TeamInterface $team */
     $team = parent::buildEntity($form, $form_state);
 
+    if (NULL === $this->orgController) {
+      $this->orgController = \Drupal::service('apigee_edge.controller.organization');
```
Comment (mxr576) [inline modules/apigee_edge_teams/src/Entity/Form/TeamForm.php]: This fixes the null problem, but how this can be NULL when it is DI-d above?

Comment (shishir-intelli) [reply modules/apigee_edge_teams/src/Entity/Form/TeamForm.php]: This issue is coming in 3x only, when added new Team field with multi-value field setting.

Comment (mxr576) [reply modules/apigee_edge_teams/src/Entity/Form/TeamForm.php]: I saw the report, but by reading the code in this class I still do not see why/how this can be NULL, when the service is injected above. 
Depending on `\Drupal::service(()` is classes only acceptable as a BC bridge that gets removed in the next major version. Is this going to be removed or have to stay?

Comment (shishir-intelli) [reply modules/apigee_edge_teams/src/Entity/Form/TeamForm.php]: This issue was caused by `$orgController` private access specifier.
Resolved

**Review by divya-intelli — APPROVED** [review]
LGTM

File: modules/apigee_edge_teams/src/Entity/Form/TeamForm.php (hunk 1 above)
Comment (mxr576) [reply modules/apigee_edge_teams/src/Entity/Form/TeamForm.php]: Ahh so the actual issue was related to https://www.drupal.org/project/drupal/issues/3110266
