### PR TITLE
[#261] Allow authentication using a username

### LINKED ISSUE #261: Portal not compatible with External Auth on Edge
**Describe the bug**
When an Edge org (private cloud) is using External Auth, they are unable to connect their portal to Edge. The configuration page requires and email address, where External Auth requires a username (no @domain.com)

**To Reproduce**
Attempt to connect to an Edge organization using External Auth with a username (not email) and password. The portal will throw an error "Invalid email address" error. When attempting to connect with an email, you will receive a 401 error as Edge can only authenticate with a username.

**Expected behavior**
Dev portal should be able to connect to an Edge org with just a username - not only an email address.

**Version Info**
8.x-1.0

### PR DESCRIPTION
**Pull request by arlina-espinoza**
Fixes #261 . It changes the username field to a textfield, and does email validation only if using the default endpoint (for public cloud).

### CODE REVIEW

**Review by cnovak — CHANGES_REQUESTED** [review]
Looks good, but can you add a test for this service to validate the functionality?

**Comment by arlina-espinoza** [comment]
@cnovak I've added a functional test, and also moved the validation from the main form submit to the _suggestions_, so that it is also checked when using the "test connection" button. Please review again. :slightly_smiling_face:

File: src/KeyEntityFormEnhancer.php [hunk 1]
```diff
@@ -88,6 +89,13 @@ final class KeyEntityFormEnhancer {
    */
   private $configFactory;
 
+  /**
+   * The email validator.
+   *
+   * @var \Drupal\Component\Utility\EmailValidatorInterface
+   */
+  protected $emailValidator;
```
Comment (mxr576) [inline src/KeyEntityFormEnhancer.php]: Using `protected` in a `final` class does not make any sense.

File: src/KeyEntityFormEnhancer.php [hunk 2]
```diff
@@ -498,10 +509,20 @@ private function createSuggestion(\Exception $exception, KeyInterface $key): Mar
...
       // the MGMT server returns HTTP 500 with an error instead of HTTP 401.
       if ($exception->getCode() === 401 || ($exception->getCode() === 500 && $exception->getEdgeErrorCode() === 'usersandroles.SsoInternalServerError')) {
-        $suggestion = $this->t('@fail_text The given username (%username) or password is incorrect.', [
-          '@fail_text' => $fail_text,
-          '%username' => $key_type->getUsername($key),
-        ]);
+
+        // If on public cloud (using the default endpoint), the username should
+        // be an email.
+        if ($key_type->getEndpointType($key) == 'default' && !$this->emailValidator->isValid($key_type->getUsername($key))) {
```
Comment (mxr576) [inline src/KeyEntityFormEnhancer.php]: Use strict comparison

File: src/Plugin/EdgeKeyTypeBase.php [hunk 3]
```diff
@@ -62,6 +62,13 @@ public function getEndpoint(KeyInterface $key): string {
     return $key->getKeyValues()['endpoint'] ?? Client::DEFAULT_ENDPOINT;
   }
 
+  /**
+   * {@inheritdoc}
+   */
+  public function getEndpointType(KeyInterface $key): string {
+    return $key->getKeyValues()['endpoint_type'] ?? 'default';
```
Comment (mxr576) [inline src/Plugin/EdgeKeyTypeBase.php]: I would probably consider introducing constants for `default` and `custom` in EdgeKeyTypeInterface because I keep seeing these magic words appearing in different places of the code. Ex.: in ApigeeAuthKeyForm.

**Review by mxr576 — CHANGES_REQUESTED** [review]
Also `$values['endpoint_type']` is alway set [here](https://github.com/apigee/apigee-edge-drupal/blob/4dc2cb8ff1aaaf4c797660e7a1ca9ba849946d29/src/Plugin/KeyInput/ApigeeAuthKeyInput.php#L112) because of this [line](https://github.com/apigee/apigee-edge-drupal/blob/4dc2cb8ff1aaaf4c797660e7a1ca9ba849946d29/src/Plugin/KeyInput/ApigeeAuthKeyInput.php#L66).

File: src/KeyEntityFormEnhancer.php (hunk 2 above)
Comment (mxr576) [inline src/KeyEntityFormEnhancer.php]: Does this change compatible with the environment variables API key storage? Because maybe the new entity_type field's definition is missing from [here](https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/src/Plugin/KeyType/ApigeeAuthKeyType.php#L42-L75) and thanks for that the environment credentials storage [does not expose](https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/src/Plugin/KeyProvider/EnvironmentVariablesKeyProvider.php#L115) an environment variable for this field. IOW, what happens if I set the value of the APIGEE_EDGE_USERNAME environment variable to an invalid email and the APIGEE_EDGE_ENDPOINT to a private org (without being able the set the endpoint type so it remains "default"). If I click on "Test connection, does it generate a suggestion that the username should be an email address?

If this is real bug then probably the same issue occurs for the `authorization_server_type` introduced in #254.

Comment (cnovak) [reply src/KeyEntityFormEnhancer.php]: @mxr576 can you explain why in this case? I am guessing you are thinking performance, but other than that I don't see an issue w/type juggling.

File: src/Plugin/KeyInput/ApigeeAuthKeyInput.php [hunk 4]
```diff
@@ -87,9 +87,9 @@ public function buildConfigurationForm(array $form, FormStateInterface $form_sta
       '#attributes' => ['autocomplete' => 'off'],
     ];
     $form['username'] = [
-      '#type' => 'email',
+      '#type' => 'textfield',
       '#title' => $this->t('Username'),
-      '#description' => $this->t("Organization user's email address that is used for authenticating with the endpoint."),
+      '#description' => $this->t("Organization username that is used for authenticating with the endpoint."),
```
Comment (cnovak) [inline src/Plugin/KeyInput/ApigeeAuthKeyInput.php]:
```suggestion
      '#description' => $this->t("Apigee user's email address or identity provider username that is used for authenticating with the endpoint."),
```
Don't think we should change to username because you don't user the username if it is an Apigee User:
Screen Shot 2019-09-25 at 9 07 37 AM

**Review by cnovak — CHANGES_REQUESTED** [review]
Need to address @mxr576 comments, and one wording change I put in.  Make sure to validate environment variables work properly.

**Comment by cnovak** [comment]
@mxr576 not sure what you mean here, is this supposed to be commenting on a specific code line?:
> Also `$values['endpoint_type']` is alway set [here](https://github.com/apigee/apigee-edge-drupal/blob/4dc2cb8ff1aaaf4c797660e7a1ca9ba849946d29/src/Plugin/KeyInput/ApigeeAuthKeyInput.php#L112) because of this [line](https://github.com/apigee/apigee-edge-drupal/blob/4dc2cb8ff1aaaf4c797660e7a1ca9ba849946d29/src/Plugin/KeyInput/ApigeeAuthKeyInput.php#L66).

File: src/Plugin/EdgeKeyTypeBase.php (hunk 3 above)
Comment (arlina-espinoza) [reply src/Plugin/EdgeKeyTypeBase.php]: Added the constants and updated appearances of `default` and `custom` to use them.

File: src/KeyEntityFormEnhancer.php (hunk 2 above)
Comment (arlina-espinoza) [reply src/KeyEntityFormEnhancer.php]: Changed to strict comparison.

File: src/KeyEntityFormEnhancer.php (hunk 1 above)
Comment (arlina-espinoza) [reply src/KeyEntityFormEnhancer.php]: Changed.

File: src/KeyEntityFormEnhancer.php (hunk 2 above)
Comment (arlina-espinoza) [reply src/KeyEntityFormEnhancer.php]: I've updated the `EdgeKeyTypeBase::getEndpointType()` method so that if the `endpoint_type` property isn't defined, it still returns the correct type, that way we can avoid adding more environment variables.

https://github.com/apigee/apigee-edge-drupal/blob/ac7ba5cf219ac0807685af4f4acc4b652b444e80/src/Plugin/EdgeKeyTypeBase.php#L73-L77

`authorization_server_type` isn't an issue, because it isn't used outside of the `ApigeeAuthKeyInput` class/form.

**Comment by arlina-espinoza** [comment]
I've addressed the recommended changes @cnovak / @mxr576, please take a look.

**Review by cnovak — APPROVED** [review]
LGTM
