### PR TITLE
[#430] Add configurable cache max age for edge entity list builder

### LINKED ISSUE #430: Status of the App is not updated immediately on the App list
## Description
When someone logs in as an authenticated user (not admin) into a site, and changes the status of an App's product in Apigee Edge's UI, the status will not change on the App list as well. Meanwhile, it's refreshed on the App's page itself.
This might be confusing for a user.
For a user who is logged in to the site as an administrator, this works as intended.
None of the cache settings (API Product caching or Developer App settings cache) affects the outcome. 

## Steps to Reproduce
1. Create an App in Drupal, append a Product and a User to it.
2. Log in to the site with the corresponding user and go to the App list.
3. In Apigee Edge's UI, change any Product's status of the App (from Approved to Revoked or vice versa).
4. Refresh the App list page.

## Actual Behavior
The status in the App list remains unchanged, whilst if you click on the App's name and go to the App page itself, the status is changed. The status on the App list will only change if a global cache rebuild is applied.

## Expected Behavior
Change the status of the App on the App list as well.

## Screenshots
On the App list: https://i.imgur.com/ndKIA69.png (status is not changed)
On the App's page: https://i.imgur.com/mmpWq5A.png (status is changed)

## Version Info
Apigee Edge Drupal integration Module 8.x-1.7, Drupal core 8.8.6

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #430

### CODE REVIEW

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php [hunk 1]
```diff
@@ -185,4 +191,14 @@ protected function getDisplaySettings(): array {
...
   }
 
+  /**
+   * Returns the cache max age.
+   *
+   * @return int
+   *   The cache max age.
+   */
+  protected function getCacheMaxAge() {
+    return 0;
```
Comment (mxr576) [inline src/Entity/ListBuilder/EdgeEntityListBuilder.php:201]: How about providing a sane default?

```php
<?php
    $config = $this->configFactory->get("apigee_edge.{$this->entityTypeId}_app_settings");
    if (!$config->isNew()) {
      return  $config ->get('cache_expiration');
    }
   return 0;
```

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php [hunk 2]
```diff
@@ -126,10 +126,20 @@ protected function buildEntityIdQuery(): QueryInterface {
...
     }
+    else {
+      $build = parent::render();
+    }
+
+    // Add cache contexts.
+    $build['#cache'] = [
+      'contexts' => $this->entityType->getListCacheContexts(),
+      'tags' => $this->entityType->getListCacheTags(),
+      'max-age' => $this->getCacheMaxAge(),
```
Comment (mxr576) [inline src/Entity/ListBuilder/EdgeEntityListBuilder.php:139]: Isn't the entity type's default cache should be considered here or it should be the same as what is stored in the entity type specific config (by default)?

**Review by mxr576 — CHANGES_REQUESTED** [review]

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php (hunk 1 above)
Comment (shadcn) [reply src/Entity/ListBuilder/EdgeEntityListBuilder.php:201]: I see but `cache_expiration` is not available for all entity types. It's up to the Edge entity list to implement the config for this and the list builder. So `0` makes sense here since we don't want to cache by default.

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php (hunk 2 above)
Comment (shadcn) [reply src/Entity/ListBuilder/EdgeEntityListBuilder.php:139]: Not sure what you mean here. Can you point me to `"what is stored in the entity type specific config (by default)"`? Thanks.

Comment (mxr576) [reply src/Entity/ListBuilder/EdgeEntityListBuilder.php:139]: Ohh, so there is no `getListCacheMaxAge()` on Drupal entity types by default, probably because of the same reason: https://github.com/apigee/apigee-edge-drupal/issues/430#issuecomment-649539244

so probably on Apigee Edge entity types, we should have a `getListCacheMaxAge()` method that returns the applicable max-age for an entity type specific list builders and it should retrieve the value from the related config.

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php (hunk 1 above)
Comment (mxr576) [reply src/Entity/ListBuilder/EdgeEntityListBuilder.php:201]: > I see but cache_expiration is not available for all entity types

let me challenge that... if this is true, why do we have a 'getCacheMaxAge()' in the base class if it not leverage by 100% of the sub-classes?

**Review by mxr576 — CHANGES_REQUESTED** [review]

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php (hunk 2 above)
Comment (shadcn) [reply src/Entity/ListBuilder/EdgeEntityListBuilder.php:139]: Yeah. Only `getListCacheContexts` and `getListCacheTags` on `EntityInterface`.

We could implement a `getListCacheMaxAge` in `EdgeEntityInterface` but not all entity types defines a `list_builder`.

I think we can leave it on the base `EdgeEntityListBuilder` class.

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php [hunk 3]
```diff
@@ -126,10 +126,20 @@ protected function buildEntityIdQuery(): QueryInterface {
...
+      $build = $this->renderUsingViewMode($settings['view_mode']);
     }
+    else {
+      $build = parent::render();
+    }
+
+    // Add cache contexts.
+    $build['#cache'] = [
+      'contexts' => $this->entityType->getListCacheContexts(),
+      'tags' => $this->entityType->getListCacheTags(),
```
Comment (arlina-espinoza) [inline src/Entity/ListBuilder/EdgeEntityListBuilder.php:138]: The entity type list cache tags and contexts are not user aware, which means the render array will get cached the same for all of the users. We need to add the `user` and maybe also `user.permissions` to  the contexts to make the render array aware that the response changes per user.

**Review by arlina-espinoza — CHANGES_REQUESTED** [review]
Looking good! Just check my comment about adding the user context. Thanks @arshad :)

File: src/Entity/ListBuilder/EdgeEntityListBuilder.php (hunk 3 above)
Comment (shadcn) [reply src/Entity/ListBuilder/EdgeEntityListBuilder.php:138]: Added. Thanks.

**Review by arlina-espinoza — APPROVED** [review]
LGTM, thanks @arshad !
