### PR TITLE
Fix 624 - updated the custom hook to use argument and fix minor issues

### LINKED ISSUE #624: Rollback or fix #609 or find an alternative solution
## Description
PR #609 was merged but there are several problems with it.

Approach 1) If we would like to keep the _current_ solution then it should be fixed, see review comments on https://github.com/apigee/apigee-edge-drupal/commit/1f15f9148f15066c6ba7584f8e9c56ac5ce654e7

Approach 2) Since even Drupal core is tending to get away Drupalism called "alter hooks" and use events, the SDKConnector should rather trigger an event instead of exposing an alter hook.

Approach 3) (This would be my preference) instead of extending the public API of the module "unnecessarily", I would verify what changes are needed to be made (if any) to allow a simple SDK connector _service decorator_ to change (extend or override) the user agent string. 

## Version Info
Latest master.

### PR DESCRIPTION
**Pull request by shishir-intelli**
Fix #624 with approach #1

1. Module name prefixed on custom hook.
2. Implemented return type.
3. Function updated with argument (`$user_agent`).
4. Removed custom hook implement from .module file.

### CODE REVIEW

File: src/SDKConnector.php [hunk 1]
```diff
@@ -250,8 +250,16 @@ private function buildCredentials(KeyInterface $key): CredentialsInterface {
...
-      $userAgent = implode('; ', $userAgent);
+      // apigee_edge module info.
+      $edge_module_info = $this->infoParser->parse($this->moduleHandler->getModule('apigee_edge')->getPathname());
+      if (!isset($edge_module_info['version'])) {
+        $edge_module_info['version'] = '2.x-dev';
+      }
+      $user_agent[] = $edge_module_info['name'] . '/' . $edge_module_info['version'];
+
+      // Get info from other modules.
+      $userAgent = \Drupal::moduleHandler()->invokeAll('apigee_edge_user_agent_string', [&$user_agent]);
```
Comment (mxr576) [inline src/SDKConnector.php]: Module handler has to be dependency-injected to the service. It also should be added as a nullable dependency with failover and a warning that it becomes a mandatory parameter in the next major version (as you can see in Drupal core).

File: src/SDKConnector.php [hunk 2]
```diff
@@ -250,8 +250,16 @@ private function buildCredentials(KeyInterface $key): CredentialsInterface {
...
+      $userAgent = !empty($userAgent) ? implode('; ', $userAgent) : implode('; ', $user_agent);
 
       self::$userAgentPrefix = $userAgent . '; Drupal/' . \Drupal::VERSION;
```
Comment (mxr576) [inline src/SDKConnector.php]: Test coverage should be extended/added for the new alterable/extendable user agent.

File: src/SDKConnector.php [hunk 3]
```diff
@@ -250,8 +250,16 @@ private function buildCredentials(KeyInterface $key): CredentialsInterface {
...
   protected function userAgentPrefix(): string {
     if (NULL === self::$userAgentPrefix) {
-      $userAgent = \Drupal::moduleHandler()->invokeAll('user_agent_string_alter');
-      $userAgent = implode('; ', $userAgent);
+      // apigee_edge module info.
+      $edge_module_info = $this->infoParser->parse($this->moduleHandler->getModule('apigee_edge')->getPathname());
+      if (!isset($edge_module_info['version'])) {
+        $edge_module_info['version'] = '2.x-dev';
+      }
+      $user_agent[] = $edge_module_info['name'] . '/' . $edge_module_info['version'];
```
Comment (mxr576) [inline src/SDKConnector.php]: I would call it `$user_agent_parts`

File: apigee_edge.api.php [hunk 4]
```diff
@@ -37,9 +37,16 @@ function hook_apigee_edge_app_listing_page_title_alter(\Drupal\Core\StringTransl
...
+ * Build user agent string.
+ *
+ * @param array $user_agent
+ *   The user agent string data.
+ *
+ * @return string
+ *   A string with module info.
  */
-function hook_user_agent_string_alter() {
+function hook_apigee_edge_user_agent_string(array &$user_agent) {
```
Comment (mxr576) [inline apigee_edge.api.php]: I would call it `$user_agent_parts`

Comment (mxr576) [reply apigee_edge.api.php]: Missing `void` return type.

File: apigee_edge.api.php [hunk 5]
```diff
@@ -37,9 +37,16 @@ function hook_apigee_edge_app_listing_page_title_alter(\Drupal\Core\StringTransl
...
+  return $user_agent;
```
Comment (mxr576) [inline apigee_edge.api.php]: If the variable is passed by reference, no return is needed. (I more real life-ish example would be better :) )

File: apigee_edge.api.php [hunk 6]
```diff
@@ -37,9 +37,16 @@ function hook_apigee_edge_app_listing_page_title_alter(\Drupal\Core\StringTransl
 }
 
 /**
- * Alters the user agent string.
+ * Build user agent string.
```
Comment (mxr576) [inline apigee_edge.api.php]: I would: Extends the default user-agent information sent by the API client.

File: src/SDKConnector.php (hunk 2 above)
Comment (mxr576) [inline src/SDKConnector.php]: It is still looks odd that the module version can be removed from the user agent string via an alter hook (yes, that is possible) but not the Drupal version suffix.
Maybe the alter hook should allow altering the complete string (e.g: `Apigee Edge/2.x-dev;Drupal/8.9.10`) and in an alter hook implementation the string should be parsed, exploded and imploded again as needed. (We intentionally introduced a format that can be easily parsed ;) ).

**Review by mxr576 — CHANGES_REQUESTED** [review]

File: src/SDKConnector.php (hunk 2 above)
Comment (mxr576) [reply src/SDKConnector.php]: @shishir-intelli First I think we should get an agreement on this because other suggested changes could become unnecessary :)

Comment (mxr576) [reply src/SDKConnector.php]: The other option is the alter hook still gets an array of user agent string parts (Component and version) that includes Apigee Edge version and Drupal version by default and a hook implementation can add new items to that array in any position, or even remove items. The user agent string would be still built in the SdkConnector to the expected format. (Probably that is the better option due to the previous sentence)

File: apigee_edge.api.php (hunk 4 above)
Comment (mxr576) [reply apigee_edge.api.php]: How about `hook_apigee_edge_user_agent_string_alter()`?

File: apigee_edge.api.php [hunk 7]
```diff
@@ -37,9 +37,16 @@ function hook_apigee_edge_app_listing_page_title_alter(\Drupal\Core\StringTransl
...
+ *
+ * @param array $user_agent
+ *   The user agent string data.
+ *
+ * @return string
+ *   A string with module info.
```
Comment (mxr576) [inline apigee_edge.api.php]: "The user agent string."

File: src/SDKConnector.php (hunk 2 above)
Comment (shishir-intelli) [reply src/SDKConnector.php]: Yes, By default Apigee Edge version and Drupal version in array and in hook implementation one can add new items or update the position, In our case m10 module info is placed at beginning of array. so now the format looks like 
`Apigee Monetization/8.x-1.11; Apigee Edge/8.x-1.24; Drupal/9.2.6 (Apigee Edge PHP Client 2.0.10; PHP/# )`

**Review by phdhiren — APPROVED** [review]
LGTM
