### PR TITLE
Fix deprecated uasort() and usort()

### LINKED ISSUE #680: Deprecated function: uasort()
Need to fix deprecated function: uasort() Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero
Test fails in php8.0

### PR DESCRIPTION
**Pull request by divya-intelli**
Closes #680 
Fixes php8.0  functional test.

### CODE REVIEW

File: src/Form/AppApiKeyAddFormBase.php [hunk 1]
```diff
@@ -209,7 +209,7 @@ protected function getApiProductsForApp(AppInterface $app): array {
 
     // Find the recently active one.
     usort($approved_credentials, function (AppCredentialInterface $a, AppCredentialInterface $b) {
-      return $a->getIssuedAt() < $b->getIssuedAt();
+      return $a->getIssuedAt() <=> $b->getIssuedAt();
```
Comment (phdhiren) [inline src/Form/AppApiKeyAddFormBase.php]: It should be `return $b->getIssuedAt() <=> $a->getIssuedAt();`

**Review by phdhiren — CHANGES_REQUESTED** [review]

**Review by phdhiren — APPROVED** [review]
LGTM
