### PR TITLE
Remove entity save on config form

### LINKED ISSUE #733: Drupal 11 with Devportal on install, gives issue on GCP credentials page
## Description
On install page while configuring GCP credentials, the next step throws installation issue.
Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a synthetic service ("kernel"). The DIC does not know how to construct this service. in Symfony\Component\DependencyInjection\ContainerBuilder->createService() (line 1093 of vendor/symfony/dependency-injection/ContainerBuilder.php).

## Expected Behavior
Installation should be completed without any errors.

## Notes
Update the forms deprecated settings is install sets.

## Version Info
Drupal 11

### PR DESCRIPTION
**Pull request by kedarkhaire**
Fixes https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/733 issue.

Saving entity on Config form creates synthetic service call, which throws issue on Drupal 11 Devportal installation.

Storing key values & other required is done by Keys module save & submit() function.

Thanks!

### CODE REVIEW

File: src/Form/AuthenticationForm.php [hunk 1]
```diff
@@ -183,8 +183,6 @@ public function save(array $form, FormStateInterface $form_state) {
     // @see https://www.drupal.org/project/key/issues/3048562
     $status = parent::save($form, $form_state);
 
-    // Save the authentication key entity id to module's configuration.
-    $this->configFactory->getEditable(static::CONFIG_NAME)->set('active_key', $this->entity->id())->save();
```
Comment (shishir-intelli) [inline src/Form/AuthenticationForm.php:187]: Why are we removing this? how do we save the `active_key` if not here?

**Review by shishir-intelli — CHANGES_REQUESTED** [review]

File: src/Form/AuthenticationForm.php (hunk 1 above)
Comment (kedarkhaire) [reply src/Form/AuthenticationForm.php:187]: Updated.
After Configs need to be set(), not save().

**Review by shishir-intelli — APPROVED** [review]
LGTM
