### PR TITLE
[#416] Myapps endpoint toggle password.

### LINKED ISSUE #416: My Apps area should not retreive the key/secret at the same time
## Description
As a security concern, the My Apps area should not retreive the key/secret at the same time. When the user clicks the view icon, it should do a get of the key.

## Steps to Reproduce
1. Go to My Apps
2. View source

## Actual Behavior
You can see both the key/secret combo

## Expected Behavior
No security info seen. 

## Notes
We did a penetration test and these bugs were found as medium/high for their purposes.

## Version Info
Machine name: apigee_edge
Version: 8.x-1.6

### PR DESCRIPTION
**Pull request by minnur**
Related to https://github.com/apigee/apigee-edge-drupal/issues/415

I implemented new endpoint that returns JSON response with credentials for a given app. Credentials are getting pulled by app name and current user.

### CODE REVIEW

File: src/Routing/EdgeDynamicRouting.php [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  /**
+   * Build routes dynamically.
+   */
+  public function routes() {
+    $route_collection = new RouteCollection();
+    $route = new Route('/admin/config/apigee-edge/app/{developer_app_by_name}/credentials',
+      [
+        '_controller' => '\Drupal\apigee_edge\Entity\ListBuilder\DeveloperAppListBuilderForDeveloper::appCredentials',
+        '_title' => 'App credentials',
+        'user' => \Drupal::currentUser()->id(),
```
Comment (mxr576) [inline src/Routing/EdgeDynamicRouting.php]: 1. Use DI.
2. Should not admins also have access to credentials of _all_ users? Since they have administer/bypass permission... 
3. This should also support team apps.

**Review by mxr576 — CHANGES_REQUESTED** [review]

File: src/Routing/EdgeDynamicRouting.php (hunk 1 above)
Comment (minnur) [reply src/Routing/EdgeDynamicRouting.php]: This is how it is currently pulling apps for current user. See Drupal\apigee_edge\ParamConverter\DeveloperAppNameConverter

File: src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php [hunk 2]
```diff
@@ -215,4 +216,21 @@ public function pageTitle(): TranslatableMarkup {
...
 
+  /**
+   * Returns app credentials.
+   *
+   * @return \Symfony\Component\HttpFoundation\JsonResponse
+   *   The app credentials.
+   */
+  public function appCredentials($developer_app_by_name): JsonResponse {
+    $payload = [];
+    if ($credentials = array_shift($developer_app_by_name->getCredentials())) {
```
Comment (mxr576) [inline src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php]: The Apigee Edge module supports app with multiple credentials, this feature should not be removed with this change.

File: src/Routing/EdgeDynamicRouting.php [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+ * Dynamically built routes.
+ */
+class EdgeDynamicRouting {
+
+  /**
+   * Build routes dynamically.
+   */
+  public function routes() {
+    $route_collection = new RouteCollection();
+    $route = new Route('/admin/config/apigee-edge/app/{developer_app_by_name}/credentials',
```
Comment (mxr576) [inline src/Routing/EdgeDynamicRouting.php]: Why should is an admin path?

File: src/Routing/EdgeDynamicRouting.php [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+/**
+ * Dynamically built routes.
+ */
+class EdgeDynamicRouting {
+
+  /**
+   * Build routes dynamically.
+   */
+  public function routes() {
```
Comment (mxr576) [inline src/Routing/EdgeDynamicRouting.php]: Missing return typehint.

**Review by mxr576 — CHANGES_REQUESTED** [review]

File: src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php (hunk 2 above)
Comment (minnur) [reply src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php]: @arlina-espinoza do you have an example of the app with multiple credentials ?

File: src/Routing/EdgeDynamicRouting.php (hunk 1 above)
Comment (mxr576) [reply src/Routing/EdgeDynamicRouting.php]: I know,I wrote it :) , but you can still use dependency injection here I think, you just need to implement the right interface. Also, probably it would be better introducing a route like the following if you would like to solve the 2nd point, user/[uid]/apps/[app]/api-keys/[api-key].
For the 3rd point, you need a team app spec endpoint.

File: src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php (hunk 2 above)
Comment (mxr576) [reply src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php]: Go to Apigee Edge MGMT UI, can you can add more than one certificate to an app on the UI, those should be visible in the devportal too even if they cannot be created on the devportal UI by default.

File: src/Routing/EdgeDynamicRouting.php (hunk 1 above)
Comment (minnur) [reply src/Routing/EdgeDynamicRouting.php]: good point. I made the change and added two routes:
/api-keys/developer/{uid}/{app_name}
/api-keys/team/{team}/{app_name}

File: src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php (hunk 2 above)
Comment (minnur) [reply src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php]: Yes, found it and made the change to support multiple credentials.

File: src/Routing/EdgeDynamicRouting.php (hunk 3 above)
Comment (minnur) [reply src/Routing/EdgeDynamicRouting.php]: Changed it and got rid of the class. Instead I put the route into the route file.

File: src/Routing/EdgeDynamicRouting.php (hunk 4 above)
Comment (minnur) [reply src/Routing/EdgeDynamicRouting.php]: Class removed, no longer relevant.

**Comment by minnur** [comment]
@arlina-espinoza @arshad do we have some code that would check user permission in teams ? I would like to add some routine that would make sure users cannot pull credentials for different developers or teams.

File: src/Controller/DeveloperAppKeysController.php [hunk 5]
```diff
@@ -0,0 +1,98 @@
+<?php
+
+/**
+ * Copyright 2018 Google Inc.
```
Comment (arlina-espinoza) [inline src/Controller/DeveloperAppKeysController.php]:
```suggestion
 * Copyright 2020 Google Inc.
```

**Review by arlina-espinoza — CHANGES_REQUESTED** [review]
> @arlina-espinoza @arshad do we have some code that would check user permission in teams ? I would like to add some routine that would make sure users cannot pull credentials for different developers or teams.

@minnur If you switch the paths to something like `/user/{user}/apps/{app}/api-keys` and `/teams/{team}/apps/{app}/api-keys`, you could take advantage of the route requirement `_app_access_check_by_app_name`: `view` to enforce a _view_ access permission. See [`DeveloperAppRouteProvider::getCanonicalRouteByDeveloper()`](https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/src/Entity/DeveloperAppRouteProvider.php#L172-L182)

File: src/Controller/DeveloperAppKeysController.php (hunk 5 above)
Comment (minnur) [reply src/Controller/DeveloperAppKeysController.php]: thanks Arlina, I am working on this.

Comment (minnur) [reply src/Controller/DeveloperAppKeysController.php]: Resolved in b4cd0f2099578240972d594490f9c43e0e22bf89

**Comment by arlina-espinoza** [comment]
@googlebot I consent.

**Review by arlina-espinoza — APPROVED** [review]
Thanks @minnur , I tested locally and fixed the tests. LGTM :+1:
